require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe HoldersController do

  # This should return the minimal set of attributes required to create a valid
  # Holder. As you add validations to Holder, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # HoldersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all holders as @holders" do
      holder = Holder.create! valid_attributes
      get :index, {}, valid_session
      assigns(:holders).should eq([holder])
    end
  end

  describe "GET show" do
    it "assigns the requested holder as @holder" do
      holder = Holder.create! valid_attributes
      get :show, {:id => holder.to_param}, valid_session
      assigns(:holder).should eq(holder)
    end
  end

  describe "GET new" do
    it "assigns a new holder as @holder" do
      get :new, {}, valid_session
      assigns(:holder).should be_a_new(Holder)
    end
  end

  describe "GET edit" do
    it "assigns the requested holder as @holder" do
      holder = Holder.create! valid_attributes
      get :edit, {:id => holder.to_param}, valid_session
      assigns(:holder).should eq(holder)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Holder" do
        expect {
          post :create, {:holder => valid_attributes}, valid_session
        }.to change(Holder, :count).by(1)
      end

      it "assigns a newly created holder as @holder" do
        post :create, {:holder => valid_attributes}, valid_session
        assigns(:holder).should be_a(Holder)
        assigns(:holder).should be_persisted
      end

      it "redirects to the created holder" do
        post :create, {:holder => valid_attributes}, valid_session
        response.should redirect_to(Holder.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved holder as @holder" do
        # Trigger the behavior that occurs when invalid params are submitted
        Holder.any_instance.stub(:save).and_return(false)
        post :create, {:holder => {}}, valid_session
        assigns(:holder).should be_a_new(Holder)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Holder.any_instance.stub(:save).and_return(false)
        post :create, {:holder => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested holder" do
        holder = Holder.create! valid_attributes
        # Assuming there are no other holders in the database, this
        # specifies that the Holder created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Holder.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => holder.to_param, :holder => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested holder as @holder" do
        holder = Holder.create! valid_attributes
        put :update, {:id => holder.to_param, :holder => valid_attributes}, valid_session
        assigns(:holder).should eq(holder)
      end

      it "redirects to the holder" do
        holder = Holder.create! valid_attributes
        put :update, {:id => holder.to_param, :holder => valid_attributes}, valid_session
        response.should redirect_to(holder)
      end
    end

    describe "with invalid params" do
      it "assigns the holder as @holder" do
        holder = Holder.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Holder.any_instance.stub(:save).and_return(false)
        put :update, {:id => holder.to_param, :holder => {}}, valid_session
        assigns(:holder).should eq(holder)
      end

      it "re-renders the 'edit' template" do
        holder = Holder.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Holder.any_instance.stub(:save).and_return(false)
        put :update, {:id => holder.to_param, :holder => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested holder" do
      holder = Holder.create! valid_attributes
      expect {
        delete :destroy, {:id => holder.to_param}, valid_session
      }.to change(Holder, :count).by(-1)
    end

    it "redirects to the holders list" do
      holder = Holder.create! valid_attributes
      delete :destroy, {:id => holder.to_param}, valid_session
      response.should redirect_to(holders_url)
    end
  end

end
